# Generated by Django 3.1.3 on 2020-12-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('americano', 'Americano'), ('italiano', 'Italiano')], default='americano', max_length=10, verbose_name='size')),
                ('slug', models.SlugField(choices=[('americano', 'Americano'), ('italiano', 'Italiano')], default='Americano', verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.ManyToManyField(to='Pizzas.PizzaSize', verbose_name='size.pizza')),
            ],
        ),
    ]
