# Generated by Django 3.1.3 on 2020-12-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='content',
            field=models.TextField(default=1, verbose_name='Content Pizza'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='Price pizza'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='title',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Name pizza'),
            preserve_default=False,
        ),
    ]
